stages:
  - test
  - deploy

test:
  image: python:3.10-slim
  stage: test
  before_script:
    - pip install flake8
    - pip install -r requirements.txt
  script:
    - flake8 --config setup.cfg webserver experiment
    - python -m unittest experiment_tests/*.py
    - cd webserver && python manage.py makemigrations && python manage.py migrate
    - python manage.py test sop.tests

upload_registry:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: docker:latest
  stage: deploy
  tags: 
    - image
  services:
    - docker:dind
  script:
    - docker build -t sop-web -f Dockerfile_web .
    - docker login -u $REGISTRY_USER -p $REGISTRY_PW $REGISTRY_URL
    - docker tag sop-web $REGISTRY_URL/sop-web:latest
    - docker push $REGISTRY_URL/sop-web:latest
    - docker build -t sop-experiment -f Dockerfile_experiment .
    - docker tag sop-experiment $REGISTRY_URL/sop-experiment:latest
    - docker push $REGISTRY_URL/sop-experiment:latest

deploy:
  needs: ["upload_registry"]
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: alpine:latest
  stage: deploy
  before_script:
    - chmod og= $SSH_KEY
    - apk update && apk add openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_IP $SSH_HOST_KEY" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -i $SSH_KEY $SSH_USER@$SSH_IP ./script.sh

