stages:
  - test
  - deploy
  
test:
  image: python:3.10-slim
  stage: test
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:20.10.16-dind
  before_script:
    - apt update
    - apt install -y curl
    - curl https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_105.0.5195.52-1_amd64.deb --output chrome.deb
    - apt install -y ./chrome.deb
    - curl https://download.docker.com/linux/debian/dists/bullseye/pool/stable/amd64/docker-ce-cli_20.10.16~3-0~debian-bullseye_amd64.deb --output docker.deb
    - apt install -y ./docker.deb
    - docker info
    - pip install flake8
    - pip install -r requirements.txt
  script:
    - flake8 --config setup.cfg webserver experiment
    - cd webserver && python manage.py makemigrations && python manage.py migrate
    - python manage.py test sop.tests

deploy:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: alpine:latest
  stage: deploy
  before_script:
    - chmod og= $SSH_KEY
    - apk update && apk add openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_IP $SSH_HOST_KEY" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -i $SSH_KEY $SSH_USER@$SSH_IP ./script.sh

