FROM python:3.10-slim

COPY ./requirements.txt ./requirements.txt

RUN pip install psycopg2-binary

RUN pip install -r requirements.txt

RUN mkdir /sop

WORKDIR /sop

COPY ./webserver ./

EXPOSE 8000

ENTRYPOINT python manage.py makemigrations && python manage.py migrate && python manage.py runserver --noreload 0.0.0.0:8000